In [2]:
import numpy as np

In [4]:
m1 = np.array([[1, 2], [100, 200]])
m2 = np.array([[12, 22], [33, 44]])

In [7]:
m2 / m1

array([[ 12.  ,  11.  ],
       [  0.33,   0.22]])

np.matrix.round(m2 / m1)

In [10]:
m1 + 5

array([[  6,   7],
       [105, 205]])

In [ ]:
m2 - 2

In [13]:
m1 * m2

array([[  12,   44],
       [3300, 8800]])

In [14]:
m1 ** 2

array([[    1,     4],
       [10000, 40000]])