In [6]:
import numpy as np;

In [8]:
a = np.array([10,20,30,40]);

print(a)

[10 20 30 40]


In [13]:
mat = np.array([[1,2], [3,4]])
print(mat[-1][-1])

4


In [20]:
mat.transpose()

array([[1, 3],
       [2, 4]])

print(mat[:1])
print(mat[1:])

In [25]:
m1 = [1,2];
m2 = [5,6];

m1 + m2

[1, 2, 5, 6]

In [29]:
m1 = np.array(m1);
m2 = np.array(m2);
m1 + m2

array([6, 8])

In [37]:
m1.sum()

mat.diagonal()

array([1, 4])

### Matrizes

In [63]:
m1 = np.array([1, 2]);
m2 = np.array([3, 4]);
m3 = np.array([5, 6]);

container = np.array([m1,m2,m3]);

print(container);

[[1 2]
 [3 4]
 [5 6]]


In [69]:
my_data = np.arange(0,20);
print(my_data)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [70]:
matriz1 = np.reshape(my_data, (5, 4));
print(matriz1);

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [72]:
print(matriz1.item(15))

15
